name: "secrets"
version: "0.1.0"
usage: "manage secrets using openstack barbican"
description: |-
  Manage secrets stored in yaml files. The encryption keys are stored in
  OpenStack Barbican, so available tokens are required for interaction.
  usage:
    $ helm secrets [command]
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/barbican"
