name: "cern"
version: "0.1.0"
usage: "manage cern secrets and deployments"
description: |-
  Manage CERN secrets and deployments
  usage:
    $ helm cern [command]
ignoreFlags: false
useTunnel: false
command: "$HELM_PLUGIN_DIR/cern"
